### ISSUE TITLE
Cannot switch between GonVim Workspaces

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#29]

**Comment by bfulop** [comment]
As a workaround, I'm just using regular Vim tags (`:tabedit` and `:lcd`), it's good enough for me.

**Comment by akiyosi** [comment]
Is it OK to understand that this is a problem only with v0.4.0 and no problem with v0.3.2 nvim?

**Comment by bfulop** [comment]
I haven't thought about it, so I removed v0.4 and installed v0.3.3 (via Homebrew). 

Unfortunately it's the same issue with v0.3.3. I can create new workspaces, but not switch between them.

**Comment by akiyosi** [comment]
Hi,
This issue can not be reproduced in my environment, but I fixed suspicious implementation in v0.3.3. If this issue occurs even in v0.3.3, I would like to continue investigating.

**Comment by akiyosi** [comment]
Umm.., 
Please tell me your `setting.toml` and `init.vim`.
Also, please check if the issue is reproduced by `/Applications/gonvim.app/Contents/MacOS/gonvim -u NONE`.

**Comment by bfulop** [comment]
Thanks, I tried launching Gonvim from the command line with `-u NONE`, but didn't seem to solve the issue.

- My [init.vim gist](https://gist.github.com/bfulop/f0995e5be149a4066e9c4f4f6660d9e0)
- My [setting.toml](https://gist.github.com/bfulop/36914d5311c2ecaa53ed4745cbc88010)

I just run `:CheckHealth`, and in fact I don't have a Python 2, 3 (v3 is outdated) and Ruby provider installed for Neovim.

**Comment by akiyosi** [comment]
Hi,
I identified the cause. This seems to happen when both the activitybar and sidebar are hidden(visible=false). I will fix it in the next version.

**Comment by bfulop** [comment]
Great news, thank you akiyosi! I will unhide the activity in the meantime to get access to workspaces switching.
